server:
  port: 8080

spring:
  application:
    name: loans

  cloud:
    config:
      enabled: true

  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

    url: jdbc:postgresql://localhost:5432/mydb
    username: user
    password: password

eureka:
  instance:
    hostname:
      localhost
    port:
      9999
  client:
    registerWithEureka:
      true
    fetchRegistry:
      false
    serviceUrl:
      defaultZone:
        http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty:
      3000
